const MESSAGES = {
  GENERAL: {
    SUCCESS: "Thành công",
    FAILED: "Thất bại",
    SERVER_ERROR: "Lỗi server, vui lòng thử lại sau",
    NOT_FOUND: "Không tìm thấy tài nguyên",
    BAD_REQUEST: "Yêu cầu không hợp lệ",
    UNAUTHORIZED: "Không được phép truy cập",
    FORBIDDEN: "Truy cập bị cấm",
  },

  AUTH: {
    LOGIN_SUCCESS: "Đăng nhập thành công",
    LOGIN_FAILED: "Đăng nhập thất bại, vui lòng kiểm tra lại thông tin",
    LOGOUT_SUCCESS: "Đăng xuất thành công",
    LOGOUT_FAILED: "Đăng xuất thất bại",
    REGISTER_SUCCESS: "Đăng ký thành công",
    REGISTER_FAILED: "Đăng ký thất bại, vui lòng thử lại",
    UNAUTHORIZED: "Bạn cần đăng nhập để thực hiện hành động này",
    INVALID_TOKEN: "Token không hợp lệ hoặc đã hết hạn",
    EMAIL_NOT_VERIFIED: "Email chưa được xác minh",
    EMAIL_VERIFIED: "Email đã được xác minh",
    PASSWORD_RESET_SUCCESS: "Đặt lại mật khẩu thành công",
    PASSWORD_RESET_FAILED: "Đặt lại mật khẩu thất bại, vui lòng thử lại",
    PASSWORD_CHANGE_SUCCESS: "Đổi mật khẩu thành công",
    PASSWORD_CHANGE_FAILED: "Đổi mật khẩu thất bại, vui lòng thử lại",
    EMAIL_ALREADY_EXISTS: "Email đã được sử dụng",
    USERNAME_ALREADY_EXISTS: "Tên người dùng đã tồn tại",
    INVALID_EMAIL: "Email không hợp lệ",
  },

  USER: {
    CREATE_SUCCESS: "Tạo người dùng thành công",
    CREATE_FAILED: "Tạo người dùng thất bại",
    UPDATE_SUCCESS: "Cập nhật người dùng thành công",
    UPDATE_FAILED: "Cập nhật người dùng thất bại",
    DELETE_SUCCESS: "Xóa người dùng thành công",
    DELETE_FAILED: "Xóa người dùng thất bại",
    NOT_FOUND: "Không tìm thấy người dùng",
  },

  CATEGORY: {
    CREATE_SUCCESS: "Tạo danh mục thành công",
    CREATE_FAILED: "Tạo danh mục thất bại",
    UPDATE_SUCCESS: "Cập nhật danh mục thành công",
    UPDATE_FAILED: "Cập nhật danh mục thất bại",
    DELETE_SUCCESS: "Xóa danh mục thành công",
    DELETE_FAILED: "Xóa danh mục thất bại",
    NOT_FOUND: "Không tìm thấy danh mục",
    EXISTS: "Danh mục đã tồn tại",
    GET_SUCCESS: "Lấy ra danh sách trả về thành công",
    SOFT_DELETE_SUCCESS: "Danh mục đã được ẩn ",
    RESTORE_SUCCESS: "Khôi phục danh mục thành công",
    RESTORE_FAILED: "Khôi phục danh mục thất bại",
  },

  SUB_CATEGORY: {
    CREATE_SUCCESS: "Tạo danh mục con thành công",
    CREATE_FAILED: "Tạo danh mục con thất bại",
    UPDATE_SUCCESS: "Cập nhật danh mục con thành công",
    UPDATE_FAILED: "Cập nhật danh mục con thất bại",
    DELETE_SUCCESS: "Xóa danh mục con thành công",
    DELETE_FAILED: "Xóa danh mục con thất bại",
    NOT_FOUND: "Không tìm thấy danh mục con",
    CREATE_PARENT_ID_ERROR: "Danh mục cha là bắt buộc",
    RESTORE_SUCCESS: "Khôi phục danh mục thành công",
    SOFT_DELETE_SUCCESS: "Xóa mềm thành công",
    RESTORE_FAILED: "Khôi phục danh mục thất bại",
  },
};
export default MESSAGES;
